export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLE_BY_CODIC = "GET_ARTICLE_BY_CODIC";

          
export const FETCHING_ARTICLES = "FETCHING_ARTICLES";
export const FETCHED_ARTICLES = "FETCHED_ARTICLES";
export const FETCHED_GET_ONE_ARTICLE = "FETCHED_GET_ONE_ARTICLE";
