export const GET_ARTICLES = "GET_ARTICLES"; 
export const GET_ARTICLE_BY_CODIC = "GET_ARTICLE_BY_CODIC"; 
export const GET_ARTICLE_INFO = "GET_PRODUCT_INFO"; 
export const GET_TAGS_ARTICLE = "GET_TAGS_ARTICLE"; 

export const FETCHING_ARTICLES = "FETCHING_ARTICLES"; 
export const FETCHED_ARTICLES = "FETCHED_ARTICLES"; 
export const FETCHED_GET_ONE_ARTICLE = "FETCHED_GET_ONE_ARTICLE"; 
export const FETCHED_ARTICLE_INFO = "FETCHED_ARTICLE_INFO"; 

//TAGS 

export const FETCHED_ARTICLE_TAGS = "FETCHED_ARTICLE_TAGS"; 